_target_: src.models.dce_module.DCELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

criterion:
  # _target_: torch.nn.MSELoss
  _target_: src.utils.loss.MixL1L2Loss


scheduler:
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 40
  gamma: 0.1

net:
  _target_: src.models.components.varnet.VarNet
  num_cascades: 5
  chans: 5
  pools: 3
  conv_size: 3
  conv_mode: '2d'
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  mask_center: false

# compile model for faster training with pytorch 2.0
compile: false
