defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss" # "val/loss" if SSDU for fastMRI dataset
  mode: "min" # "min" if SSDU for fastMRI dataset
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss" # "val/loss" if SSDU for fastMRI dataset
  patience: 10
  mode: "min" # "min" if SSDU for fastMRI dataset

model_summary:
  max_depth: -1
